name: Terraform Review

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '.github/workflows/terraform-review.yml'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-review:
    runs-on: ubuntu-latest
    name: Review Terraform Changes
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init
        run: terraform init
        env:
          TF_IN_AUTOMATION: true

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=plan.out -no-color
        env:
          TF_IN_AUTOMATION: true

      - name: Review Terraform Changes
        uses: seii-saintway/terraform-reviewer@main
        with:
          aws_region: ap-northeast-1
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          model_id: anthropic.claude-3-haiku-20240307-v1:0
          terraform_plan_file: plan.out
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment Plan (on failure)
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            if (fs.existsSync('plan.out')) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '❌ Terraform plan failed. Please check the workflow logs for details.'
              });
            }